site_name: Documentação 4SUP
site_description: Manual técnico do GesOper 4SUP — Portal Web e Aplicativo
site_url: https://example.com
repo_url: https://example.com/repo
theme:
  name: material
  language: pt
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: blue
      accent: indigo
    - scheme: slate
      primary: blue
      accent: indigo
  icon:
    repo: material/source-repository
extra:
  social:
    - icon: fontawesome/brands/whatsapp
      link: https://wa.me/00000000000
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
nav:
  - Introdução: index.md
  - Configuração:
      - Habilitar o 4SUP: configuracao/habilitar.md
      - Tabelas de Apoio: configuracao/tabelas.md
  - Portal Web:
      - Agenda: portal/agenda.md
      - Painel & Mapa: portal/painel_mapa.md
      - Chat & Relatórios: portal/chat_relatorios.md
      - Configurações: portal/configuracoes.md
  - Aplicativo:
      - Visão geral: app/index.md
